stinkomanlevels/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^stinkomanlevels/', include('stinkomanlevels.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # (r'^admin/(.*)', admin.site.root),
)

urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template, redirect_to

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^stinkomanlevels/', include('stinkomanlevels.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),

    # legacy urls
    (r'^confirm.cgi$', 'stinkomanlevels.main.views.confirm_legacy'),

    (r'^img/(?P<id>.+)$', redirect_to, {'url': "/media/img/%(id)s"}),
    (r'^oldlevels/$', redirect_to, {'url': "/media/legacy-levels/"}),
    (r'^oldlevels/(?P<id>.+)$', redirect_to, {'url': "/media/legacy-levels/%(id)s"}),
    (r'^levels/(?P<id>.+)$', redirect_to, {'url': "/media/levels/%(id)s"}),
    (r'^style/(?P<id>.+)$', redirect_to, {'url': "/media/img/%(id)s"}),
    (r'^play/(?P<level>.+)/externalSwf/(?P<id>.+)$', redirect_to,
        {'url': "/media/swf/externalSwf/%(id)s"}),
    (r'^play/externalSwf/(?P<id>.+)$', redirect_to,
        {'url': "/media/swf/externalSwf/%(id)s"}),
    (r'^play/(?P<id>.+)/objectLibrary\.swf$', redirect_to,
        {'url': "/media/swf/objectLibrary.swf"}),
    (r'^play/objectLibrary\.swf$', redirect_to,
        {'url': "/media/swf/objectLibrary.swf"}),
    (r'^play/(?P<id>.+)/stinkogame\.swf$', redirect_to,
        {'url': "/media/swf/stinkogame.swf"}),
    (r'^play/stinkogame\.swf$', redirect_to,
        {'url': "/media/swf/stinkogame.swf"}),
    (r'^common\.js$', redirect_to, {'url': "/media/js/common.js"}),
    (r'^robots\.txt$', redirect_to, {'url': "/media/robots.txt"}),
    (r'^favicon\.ico$', redirect_to, {'url': "/media/favicon.ico"}),
    (r'^style\.css$', redirect_to, {'url': "/media/css/style.css"}),
    (r'^StinkomanLE-9\.4\.1\.exe$', redirect_to, {'url': "/media/downloads/StinkomanLE-9.4.1.exe"}),

    # redirects for levels in game
    (r'^play/(.+)/levelData/level1\.(\d+)\.(\d+)\.xml$', 'stinkomanlevels.main.views.level_xml'),

    # views
    (r'^$', 'stinkomanlevels.main.views.home'),
    (r'^browse/$', 'stinkomanlevels.main.views.browse'),
    (r'^dashboard/$', 'stinkomanlevels.main.views.dashboard'),
    (r'^download/$', direct_to_template, {'template': 'download.html'}),
    (r'^edit/(.+)/$', 'stinkomanlevels.main.views.edit'),
    (r'^login/$', 'stinkomanlevels.main.views.user_login'),
    (r'^logout/$', 'stinkomanlevels.main.views.user_logout'),
    (r'^namecheck/$', 'stinkomanlevels.main.views.namecheck'),
    (r'^play/(.+)/$', 'stinkomanlevels.main.views.play'),
    (r'^post/$', 'stinkomanlevels.main.views.post'),
    (r'^rate/(.+)/(-?\d+)/$', 'stinkomanlevels.main.views.rate'),
    (r'^submit/$', 'stinkomanlevels.main.views.submit'),
    (r'^upload/$', 'stinkomanlevels.main.views.upload'),
    (r'^user/(.+)/$', 'stinkomanlevels.main.views.user'),
    (r'^register/$', 'stinkomanlevels.main.views.register'),
    (r'^register/pending/$', direct_to_template, {'template': 'pending.html'}),
    (r'^confirm/(.+)/(.+)$', 'stinkomanlevels.main.views.confirm'),
)

main/forms.py
from django import forms

from stinkomanlevels.main.models import *

class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(max_length=50, widget=forms.widgets.PasswordInput())
    next_url = forms.CharField(max_length=256, widget=forms.HiddenInput)

class NewCommentForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea(attrs={'cols':'55','rows':'8'}))

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=24)
    email = forms.EmailField(max_length=32)
    password = forms.CharField(max_length=50, widget=forms.widgets.PasswordInput())
    confirm_password = forms.CharField(max_length=50, widget=forms.widgets.PasswordInput())
    
    def clean_confirm_password(self):
        password1 = self.cleaned_data['password']
        password2 = self.cleaned_data['confirm_password']
        if password1 != password2:
            raise forms.ValidationError("Your passwords do not match.")

        return password2

    def clean_username(self):
        username = self.cleaned_data['username']

        if User.objects.filter(username=username).count() > 0:
            raise forms.ValidationError(f"The user '{username}' already exists.")

        return username
   
    def clean_email(self):
        email = self.cleaned_data['email']

        if User.objects.filter(email=email).count() > 0:
            raise forms.ValidationError("This email address already exists.")

        return email
   
class UploadLevelForm(forms.Form):
    STAGE_CHOICES = (
        ('Level 1: Go Home!', (
                ('1.1', 'Stage 1.1'),
                ('1.2', 'Stage 1.2'),
            ),
        ),
        ('Level 2: Pick a Bone!', (
                ('2.1', 'Stage 2.1'),
                ('2.2', 'Stage 2.2'),
            ),
        ),
        ('Level 3: Dumb Wall!', (
                ('3.3', 'Stage 3.3'),
            ),
        ),
        ('Level 4: Fisticuff!', (
                ('4.1', 'Stage 4.1'),
                ('4.2', 'Stage 4.2'),
                ('4.3', 'Stage 4.3'),
            ),
        ),
        ('Level 5: Oh, the Moon!', (
                ('5.1', 'Stage 5.1'),
                ('5.2', 'Stage 5.2'),
                ('5.3', 'Stage 5.3'),
            ),
        ),
        ('Level 6: Stratosfear!', (
                ('6.1', 'Stage 6.1'),
                ('6.2', 'Stage 6.2'),
                ('6.3', 'Stage 6.3'),
            ),
        ),
        ('Level 7: Ice 2 Meet U!', (
                ('7.1', 'Stage 7.1'),
                ('7.2', 'Stage 7.2'),
                ('7.3', 'Stage 7.3'),
            ),
        ),
        ('Level 8: Negatory!', (
                ('8.1', 'Stage 8.1'),
                ('8.2', 'Stage 8.2'),
                ('8.3', 'Stage 8.3'),
            ),
        ),
        ('Level 9: Turbolence!', (
                ('9.1', 'Stage 9.1'),
                ('9.2', 'Stage 9.2'),
                ('9.3', 'Stage 9.3'),
            ),
        ),
    )
    title = forms.CharField(max_length=32, required=False)
    stage = forms.ChoiceField(choices=STAGE_CHOICES)
    difficulty = forms.ChoiceField(choices=Level.DIFFICULTY_CHOICES)
    length = forms.ChoiceField(choices=Level.LENGTH_CHOICES)
    description = forms.CharField(required=False, max_length=2048, widget=forms.Textarea(attrs={'cols':'32','rows':'6'}))
    xml_code = forms.CharField(required=False, widget=forms.Textarea(attrs={'cols':'30', 'rows':'12'}))
    xml_file = forms.FileField(required=False)

    def clean_title(self):
        title = self.cleaned_data['title']

        if Level.objects.filter(title=title).count() > 0:
            raise forms.ValidationError(f"The level title '{title}' already exists.")

        return title

    def clean_xml_file(self):
        xml_code = self.cleaned_data['xml_code']
        xml_file = self.cleaned_data['xml_file']

        if len(xml_code) == 0 and xml_file is None:
            raise forms.ValidationError("You must supply either xml pasted in the box or a file to upload.")

        return xml_file

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
<title>{% block title %}Custom Stinkoman Levels{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{% block css %}{{ MEDIA_URL }}css/style.css{% endblock %}" />
<link rel="shortcut icon" href="{{ MEDIA_URL }}favicon.ico" type="image/x-icon" />
<script type="text/javascript" language="JavaScript" src="{{ MEDIA_URL }}js/common.js"></script>
{% block extra_header %}{% endblock %}
</head>
<body>
<div id="wrapper">
    <div id="menu">
        <h1>Custom Stinkoman Levels</h1>
        <div id="nav">
            <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/browse/">Browse</a></li>

            <li><a href="/submit/">Submit</a></li>
            <li><a href="/download/">Download</a></li>
            </ul>
        </div>
        {% if user.is_authenticated %}
        <div id="login">
            <ul>
            <li>
            {% with user.get_profile as profile %}
            {% include 'username.html' %}
            {% endwith %}
            </li>
            <li><a href="/dashboard/">Dashboard</a></li>
            <li><a href="/logout/">Log out</a></li>
            </ul>
        </div>
        {% else %}
        <div id="login">
            <ul>
            <li><a href="/login/?next={{ request_url }}">Log in</a></li>
            <li><a href="/register/">Register</a></li>
            </ul>
        </div>
        {% endif %}

    </div>
    <div id="content">
        {% block content %}
        {% endblock %}
    <div class="clear"><br /></div>
    </div>

    <div id="copy">
        <div>
            Current users online: 
            {% if online_profiles %}
                {% for profile in online_profiles %}
                    {% include 'username.html' %}
                {% endfor %}
            {% else %}
                None
            {% endif %}
        </div>
        <br />
        <div>
            &copy; 2008 <a href="http://www.superjoesoftware.com/">Superjoe Software</a>
        </div>
        <div>
            Stinkoman is owned and copyrighted by <a href="http://www.homestarrunner.com">Homestar Runner</a>. See the <a href="http://www.homestarrunner.com/stinkogame/v7/stinkogame.html">original game</a>.
        </div>
    </div>
</div>
</body>
</html> 

templates/confirm_failure.html
{% extends 'base.html' %}

{% block title %}Account Activation Status - {{ block.super }}{% endblock %}

{% block content %}
    <h2>Unable to Activate Account</h2>
    <p>
        {{ err_msg }}
    </p>
{% endblock %}

templates/confirm_success.html
{% extends 'base.html' %}

{% block title %}Account Activated - {{ block.super }}{% endblock %}

{% block content %}
    <h2>Account Activated</h2>
    <p>
        Your account was successfully activated. You may now <a href="/login/">Log in.</a>
    </p>
{% endblock %}

templates/edit.html
{% extends 'base.html' %}

{% block title %}Edit {{ level.title }} - {{ block.super }}{% endblock %}

{% block content %}
    <h2>Edit {{ level.title }}</h2>
    {% with 1 as editing %}
    {% include 'level_form.html' %}
    {% endwith %}
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
    <h2>Welcome!</h2>
    <p>
    Welcome to the Custom Stinkoman Levels site, where you can upload your own
    alterations of Stinkoman levels for all to see. If you don't have it yet,
    grab the <a href="/download/">level editor</a> and get to work.
    </p>
    <h2>Your old stuff</h2>
    <p>
    If you were a part of this way back when, I still have your levels. <a href="{{ MEDIA_URL }}legacy-levels">Find your stuff</a> and upload it again please.
    </p>
    
    {% with new_levels as levels %}
    {% with "New Levels" as heading %}
        {% include 'level_table.html' %}
    {% endwith %}
    {% endwith %}

    {% with top_levels as levels %}
    {% with "Top Levels" as heading %}
        {% include 'level_table.html' %}
    {% endwith %}
    {% endwith %}

{% endblock %}

templates/level_form.html
{% if err_msg %}
<p>{{ err_msg }}
{% endif %}
<form action="." method="post" enctype="multipart/form-data">
    <table class="layout">
        <tr>
            <td align="right">
                <label for="id_title">Title:</label> <br />
            </td>
            <td>
                {% ifequal editing 1 %}
                <p>You can't change this because it would change the
                URL of the level, and people might have linked to it.
                </p>
                {% else %}
                    {{ form.title.errors }} <br />
                    {{ form.title }}
                {% endifequal %}
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="id_stage">Stage:</label> <br />
            </td>
            <td>
                {{ form.stage.errors }} <br />
                {{ form.stage }}
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="id_difficulty">Difficulty:</label> <br />
            </td>
            <td>
                {{ form.difficulty.errors }} <br />
                {{ form.difficulty }}
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="id_length">Length:</label> <br />
            </td>
            <td>
                {{ form.length.errors }} <br />
                {{ form.length }}
            </td>
        </tr>
        <tr> <td colspan="2">&nbsp;</td></tr>
        <tr>
            <td align="right">
                <label for="id_description">Description:</label> <br />
            </td>
            <td>
                {{ form.description.errors }} <br />
                {{ form.description }}
            </td>
        </tr>
        <tr><td colspan="2">&nbsp;</td></tr>
        <tr><td colspan="2">
            Paste the XML code into the box or upload the level.
        </td></tr>
        <tr> <td colspan="2">
            <table class="layout">
                <tr>
                    <td>
                        {{ form.xml_code.errors }} <br />
                        {{ form.xml_code }}
                    </td>
                    <td>
                        {{ form.xml_file.errors }} <br />
                        {{ form.xml_file }}
                    </td>
                </tr>
            </table>
        </td></tr>
        <tr>
            <td colspan="2" align="center">
                <input type="submit" value="Upload" />
            </td>
        </tr>
    </table>
</form>

templates/level_table.html
<div class="tablesection">
    <div class="tableblock">
        <h3>{{ heading }}</h3>
        <table>
            <tr>
                <th>Level</th>
                <th>Creator</th>
                <th>Rating</th>
            </tr>
            {% for level in levels %}
                <tr class="{% cycle 'even' 'odd' %}">
                    <td><a href="/play/{{ level.title }}/">{{ level.title }}</a></td>
                    <td>
                        {% with level.author as profile %}
                        {% include 'username.html' %}
                        {% endwith %}
                    </td>
                    <td>{{ level.rating }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
</div>

templates/login.html
{% extends 'base.html' %}

{% block title %}Log in - {{ block.super }}{% endblock %}

{% block content %}
    {% if err_msg %}
    <p>{{ err_msg }}</p>
    {% endif %}
    <form action="." method="post">
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Sign in" />
    </form>
{% endblock %}

templates/pending.html
{% extends 'base.html' %}

{% block title %}Account Created - {{ block.super }}{% endblock %}

{% block content %}
<h2>Account created</h2>
<p>
    We used to do email verification but not anymore! Just click this activation link to continue:
</p>
<p>
  <a href="/confirm/{{ username }}/{{ code }}">Activate!</a>
</p>
{% endblock %}

templates/play.html
{% extends 'base.html' %}

{% block title %}{{ level.title }} - {{ block.super }}{% endblock %}

{% block extra_header %}
<script type="text/javascript">
function rate(score) {
    var xmlHttp = newAjax();

    xmlHttp.onreadystatechange = function(){
        if( xmlHttp.readyState == 4){
            objById("rate").innerHTML = xmlHttp.responseText;
        }
    }

    xmlHttp.open("GET", "/rate/{{ level.title }}/"+escape(score)+"/", true);
    xmlHttp.send(null);
}
</script>
{% endblock %}

{% block content %}
<div id="gameinfo">
    {% if user.is_authenticated %}
        {% ifequal user.get_profile level.author %}
            <span class="edit"><a href="/edit/{{ level.title }}/">(edit)</a></span>
        {% endifequal %}
    {% endif %}
    <h3>Level Info</h3>
    Author:
    {% with level.author as profile %}
    {% include 'username.html' %}
    {% endwith %}
    <br />
    Length: {{ level.length_str }} <br />
    Difficulty: {{ level.difficulty_str }} <br />
    Rating: {{ level.rating }} <br />
    <br />
    <div id="gamedesc">
    {% if level.description %}
        {{ level.description }}
    {% else %}
        The author has not entered any notes.
    {% endif %}
    </div>
    <p>
    {% ifequal level.minor_stage 3 %}
        This is a boss level. Press &quot;Continute&quot; and select
        <u>Stage {{ level.major_stage }}.{{ level.minor_stage }}</u>
        to play this level.
    {% else %}
        This level is meant to be played on
        <u>Stage {{ level.major_stage }}.{{ level.minor_stage }}</u>;
        make sure you press &quot;Continute&quot; and select that stage!
    {% endifequal %}
    </p>
</div>

<div id="game">
    <h2><span class="supertext"><a href="{{ MEDIA_URL }}levels/{{ level.file }}">Download ({{ level_size|filesizeformat }})</a></span>{{ level.title }}</h2>
   <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0" width="550" height="400">
   <param name="movie" value="stinkogame.swf">
   <param name="quality" value="low">
   <embed src="stinkogame.swf" quality="low" width="550" height="400" name="video" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer">
   </embed>
   </object>
   <div id="rate">
   {% include 'rate_response.html' %}
   </div>
</div>

<div id="comments">
    <h3>Level Reviews</h3>
    <div id="reviews">
    {% if level_reviews %}
        {% for comment in level_reviews %}
        <div class="{% cycle 'odd' 'even' %}">
        <h4>{{ comment.date_created|date:"M j, Y" }} by
        {% with comment.owner as profile %}
        {% include 'username.html' %}
        {% endwith %}
        </h4>
        {{ comment.text }}
        </div>
        {% endfor %}
    {% else %}
        <p>No one has posted a review for this level yet.</p>
    {% endif %}
    </div>
    <h3>Post a Review</h3>
    <div id="reviewform">
    {% if user.is_authenticated %}
        <form action="." method="post">
            {{ form.content }} <br />
            <input type="submit" value="Post" />
        </form>
    {% else %}
        <a href="/login/?next=/play/{{ level.title }}/">Log in</a> to post a review.</a>
    {% endif %}
    </div>
</div>
{% endblock %}

templates/rate_response.html
{% if user.is_authenticated %}
    {% ifequal user_rating 0 %}   
        Rate this level: <a href="javascript:rate(-1);">-1</a>
        <a href="javascript:rate(1);">+1</a>
    {% else %}
        You rated this level {{ user_rating }}. <a href="javascript:rate(0);">Undo</a>
    {% endifequal %}
{% else %}
    <a href="/login/?next=/play/{{ level.title }}/">Log in</a> to rate levels.</a>
{% endif %}

templates/register.html
{% extends 'base.html' %}

{% block title %}Create an account - {{ block.super }}{% endblock %}

{% block content %}
    <h2>Create an account</h2>
    {% if err_msg %}
    <p>{{ err_msg }}</p>
    {% endif %}
    <form action="." method="post">
        <table class="form-table">
            {{ form.as_table }}
        </table>
        <input type="submit" value="Register" />
    </form>
    <h2>Already have an account?</h2>
    <a href="/login/">Log in.</a>
{% endblock %}

templates/submit.html
{% extends 'base.html' %}

{% block title %}Submission Form - {{ block.super }}{% endblock %}

{% block content %}
    <h2>Submit a new Stinkoman Level</h2>
    {% if user.is_authenticated %}
        {% with 0 as editing %}
            {% include 'level_form.html' %}
        {% endwith %}
    {% else %}
        <p>You must <a href="/register/">register an account</a> to upload a new level. It's free and doesn't require much information.</p>
        <p>If you already have an account, <a href="/login/?next=/submit/">log in</a>.</p>
    {% endif %}
{% endblock %}

templates/username.html
<a href="/user/{{ profile.user.username }}/">{{ profile }} <span class="points">({{ profile.points }})</span></a>